dependencies:
  - OpenZeppelin/openzeppelin-contracts@5.0.0
  - smartcontractkit/chainlink-brownie-contracts@0.8.0
compiler:
  solc:
    version: 0.8.21
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@5.0.0"
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.8.0"
dotenv: .env
wallets:
  from_key_1: ${PRIVATE_KEY_1}
  from_key_2: ${PRIVATE_KEY_2}
  from_key_3: ${PRIVATE_KEY_3}
  # from_key: ${PRIVATE_KEY}
rpcs:
  infura_mainnet: ${WEB3_INFURA_PROJECT_ID}
networks:
  development:
    verify: False
  arbitrum-main-fork:
    verify: False
    dex_router_address: "0x1b02dA8Cb0d097eB8D57A175b88c7D8b47997506" # ARBITRUM Sushi
    dex_factory_address: "0xc35DADB65012eC5796536bD9864eD8773aBc74C4" # ARBITRUM Sushi
    dex_main_token_address: "0x82af49447d8a07e3bd95bd0d56f35241523fbab1" # WETH
    native_token_data_feed_address: "0x639fe6ab55c921f74e7fac1ee960c0b6293ba612" # ETH/USD
    deposit_token_address: "0xff970a61a04b1ca14834a43f5de4533ebddb5cc8" #USDC.e
    # deposit_token_address: "0xfd086bc7cd5c481dcc9c85ebe478a1c0b69fcbb9" # USDT
    # deposit_token_address: "0x912ce59144191c1204e64559fe8253a0e49e6548" # ARB
    # deposit_token_address: "0x82af49447d8a07e3bd95bd0d56f35241523fbab1" # WETH
    buy_token_addresses: [
        "0xfc5a1a6eb076a2c7ad06ed22c90d7e710e35ad0a",
        "0x912ce59144191c1204e64559fe8253a0e49e6548",
      ] # GMX + ARB
    vault_name: "GMX/ARB DCA Vault"
    vault_symbol: "GMX/ARB_DCA"
    vaults_factory_address: "0x57da7DFAD549e8fB003a8C5373010F17deb3fc7F"
    controller_address: "0xa0d180f4c5b3B48144dFfC0Bf48ce2191Ec87bed"
    worker_address: "0xFf5694903A22a7Ca13e25bc5C2aCA37fb91ad4f5"
    treasury_address: "0x92B6c99bf8b26B78Bc064F96Dc80640BD709e184"
    resolver_address: "0x7A00964A733250d6a65154bC79414Bc31b5161DC"
    token_not_paired_with_weth_address: "0x55678cd083fcdc2947a0df635c93c838c89454a3" # LON
    too_many_buy_token_addresses:
      [
        "0xfc5a1a6eb076a2c7ad06ed22c90d7e710e35ad0a",
        "0x82af49447d8a07e3bd95bd0d56f35241523fbab1",
        "0x912ce59144191c1204e64559fe8253a0e49e6548",
        "0x51318b7d00db7acc4026c88c3952b66278b6a67f",
        "0xfa7f8980b0f1e64a2062791cc3b0871572f1f7f0",
        "0x3d9907f9a368ad0a51be60f7da3b97cf940982d8",
      ]
    whitelisted_deposit_assets: [
        ############ STABLE ############
        # USDC.e:
        [
          "0xff970a61a04b1ca14834a43f5de4533ebddb5cc8", # asset_address
          0, # asset_type: STABLE
          "0x50834f3163758fcc1df9973b6e91f0f0f0434ad3", # oracle_address
          True, # is_active
        ],
        # USDC:
        [
          "0xaf88d065e77c8cc2239327c5edb3a432268e5831", # asset_address
          0, # asset_type: STABLE
          "0x50834f3163758fcc1df9973b6e91f0f0f0434ad3", # oracle_address
          True, # is_active
        ],
        # USDT:
        [
          "0xfd086bc7cd5c481dcc9c85ebe478a1c0b69fcbb9", # asset_address
          0, # asset_type: STABLE
          "0x3f3f5df88dc9f13eac63df89ec16ef6e7e25dde7", # oracle_address
          True, # is_active
        ],
        # DAI:
        [
          "0xda10009cbd5d07dd0cecc66161fc93d7c9000da1", # asset_address
          0, # asset_type: STABLE
          "0xc5c8e77b397e531b8ec06bfb0048328b30e9ecfb", # oracle_address
          True, # is_active
        ],
        ############ ETH_BTC ############
        # WETH:
        [
          "0x82aF49447D8a07e3bd95BD0d56f35241523fBab1", # asset_address
          1, # asset_type: ETH_BTC
          "0x639Fe6ab55C921f74e7fac1ee960C0B6293ba612", # oracle_address
          True, # is_active
        ],
        # WBTC:
        [
          "0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f", # asset_address
          1, # asset_type: ETH_BTC
          "0xd0c7101eacbb49f3decccc166d238410d6d46d57", # oracle_address
          True, # is_active
        ],
        ############ BLUE_CHIP ############
        # LINK:
        [
          "0xf97f4df75117a78c1a5a0dbb814af92458539fb4", # asset_address
          2, # asset_type: BLUE_CHIP
          "0x86e53cf1b870786351da77a57575e79cb55812cb", # oracle_address
          True, # is_active
        ],
        # UNI:
        [
          "0xfa7f8980b0f1e64a2062791cc3b0871572f1f7f0", # asset_address
          2, # asset_type: BLUE_CHIP
          "0x9c917083fdb403ab5adbec26ee294f6ecada2720", # oracle_address
          True, # is_active
        ],
        # SUSHI:
        [
          "0xd4d42f0b6def4ce0383636770ef773390d85c61a", # asset_address
          2, # asset_type: BLUE_CHIP
          "0xb2a8ba74cbca38508ba1632761b56c897060147c", # oracle_address
          True, # is_active
        ],
        # COMP:
        [
          "0x354a6da3fcde098f8389cad84b0182725c6c91de", # asset_address
          2, # asset_type: BLUE_CHIP
          "0xe7c53ffd03eb6cef7d208bc4c13446c76d1e5884", # oracle_address
          True, # is_active
        ],
        # CRV:
        [
          "0x11cdb42b0eb46d95f990bedd4695a6e3fa034978", # asset_address
          2, # asset_type: BLUE_CHIP
          "0xaebda2c976cfd1ee1977eac079b4382acb849325", # oracle_address
          True, # is_active
        ],
        # FXS:
        [
          "0x9d2f299715d94d8a7e6f5eaa8e654e8c74a988a7", # asset_address
          2, # asset_type: BLUE_CHIP
          "0x36a121448d74fa81450c992a1a44b9b7377cd3a5", # oracle_address
          True, # is_active
        ],
        # GMX:
        [
          "0xfc5a1a6eb076a2c7ad06ed22c90d7e710e35ad0a", # asset_address
          2, # asset_type: BLUE_CHIP
          "0xdb98056fecfff59d032ab628337a4887110df3db", # oracle_address
          True, # is_active
        ],
        # ARB:
        [
          "0x912ce59144191c1204e64559fe8253a0e49e6548", # asset_address
          2, # asset_type: BLUE_CHIP
          "0xb2a824043730fe05f3da2efafa1cbbe83fa548d6", # oracle_address
          True, # is_active
        ],
        # LDO:
        [
          "0x13ad51ed4f1b7e9dc168d8a00cb3f4ddd85efa60", # asset_address
          2, # asset_type: BLUE_CHIP
          "0xa43a34030088e6510feccfb77e88ee5e7ed0fe64", # oracle_address
          True, # is_active
        ],
      ]
    not_whitelisted_token_address_example: "0x09e18590e8f76b6cf471b3cd75fe1a1a9d2b2c2b" # AIDOGE - This token must have a pair created at the used dex
  arbitrum-main:
    verify: True
    dex_router_address: "0x1b02dA8Cb0d097eB8D57A175b88c7D8b47997506" # ARBITRUM Sushi
    dex_factory_address: "0xc35DADB65012eC5796536bD9864eD8773aBc74C4" # ARBITRUM Sushi
    dex_main_token_address: "0x82af49447d8a07e3bd95bd0d56f35241523fbab1" # WETH
    native_token_data_feed_address: "0x639fe6ab55c921f74e7fac1ee960c0b6293ba612" # ETH/USD
    deposit_token_address: "0xff970a61a04b1ca14834a43f5de4533ebddb5cc8" # USDC.e
    # deposit_token_address: "0xfd086bc7cd5c481dcc9c85ebe478a1c0b69fcbb9" # USDT
    # deposit_token_address: "0x912ce59144191c1204e64559fe8253a0e49e6548" # ARB
    # deposit_token_address: "0x82af49447d8a07e3bd95bd0d56f35241523fbab1" # WETH
    buy_token_addresses: [
        "0xfc5a1a6eb076a2c7ad06ed22c90d7e710e35ad0a",
        "0x912ce59144191c1204e64559fe8253a0e49e6548",
      ] # GMX + ARB
    vault_name: "GMX/ARB DCA Vault"
    vault_symbol: "GMX/ARB_DCA"
    vaults_factory_address: "0x57da7DFAD549e8fB003a8C5373010F17deb3fc7F"
    controller_address: "0xa0d180f4c5b3B48144dFfC0Bf48ce2191Ec87bed"
    worker_address: "0xFf5694903A22a7Ca13e25bc5C2aCA37fb91ad4f5"
    treasury_address: "0x92B6c99bf8b26B78Bc064F96Dc80640BD709e184"
    resolver_address: "0x7A00964A733250d6a65154bC79414Bc31b5161DC"
    token_not_paired_with_weth_address: "0x55678cd083fcdc2947a0df635c93c838c89454a3" # LON
    too_many_buy_token_addresses:
      [
        "0xfc5a1a6eb076a2c7ad06ed22c90d7e710e35ad0a",
        "0x82af49447d8a07e3bd95bd0d56f35241523fbab1",
        "0x912ce59144191c1204e64559fe8253a0e49e6548",
        "0x51318b7d00db7acc4026c88c3952b66278b6a67f",
        "0xfa7f8980b0f1e64a2062791cc3b0871572f1f7f0",
        "0x3d9907f9a368ad0a51be60f7da3b97cf940982d8",
      ]
    whitelisted_deposit_assets: [
        ############ STABLE ############
        # USDC.e:
        [
          "0xff970a61a04b1ca14834a43f5de4533ebddb5cc8", # asset_address
          0, # asset_type: STABLE
          "0x50834f3163758fcc1df9973b6e91f0f0f0434ad3", # oracle_address
          True, # is_active
        ],
        # USDC:
        [
          "0xaf88d065e77c8cc2239327c5edb3a432268e5831", # asset_address
          0, # asset_type: STABLE
          "0x50834f3163758fcc1df9973b6e91f0f0f0434ad3", # oracle_address
          True, # is_active
        ],
        # USDT:
        [
          "0xfd086bc7cd5c481dcc9c85ebe478a1c0b69fcbb9", # asset_address
          0, # asset_type: STABLE
          "0x3f3f5df88dc9f13eac63df89ec16ef6e7e25dde7", # oracle_address
          True, # is_active
        ],
        # DAI:
        [
          "0xda10009cbd5d07dd0cecc66161fc93d7c9000da1", # asset_address
          0, # asset_type: STABLE
          "0xc5c8e77b397e531b8ec06bfb0048328b30e9ecfb", # oracle_address
          True, # is_active
        ],
        ############ ETH_BTC ############
        # WETH:
        [
          "0x82aF49447D8a07e3bd95BD0d56f35241523fBab1", # asset_address
          1, # asset_type: ETH_BTC
          "0x639Fe6ab55C921f74e7fac1ee960C0B6293ba612", # oracle_address
          True, # is_active
        ],
        # WBTC:
        [
          "0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f", # asset_address
          1, # asset_type: ETH_BTC
          "0xd0c7101eacbb49f3decccc166d238410d6d46d57", # oracle_address
          True, # is_active
        ],
        ############ BLUE_CHIP ############
        # LINK:
        [
          "0xf97f4df75117a78c1a5a0dbb814af92458539fb4", # asset_address
          2, # asset_type: BLUE_CHIP
          "0x86e53cf1b870786351da77a57575e79cb55812cb", # oracle_address
          True, # is_active
        ],
        # UNI:
        [
          "0xfa7f8980b0f1e64a2062791cc3b0871572f1f7f0", # asset_address
          2, # asset_type: BLUE_CHIP
          "0x9c917083fdb403ab5adbec26ee294f6ecada2720", # oracle_address
          True, # is_active
        ],
        # SUSHI:
        [
          "0xd4d42f0b6def4ce0383636770ef773390d85c61a", # asset_address
          2, # asset_type: BLUE_CHIP
          "0xb2a8ba74cbca38508ba1632761b56c897060147c", # oracle_address
          True, # is_active
        ],
        # COMP:
        [
          "0x354a6da3fcde098f8389cad84b0182725c6c91de", # asset_address
          2, # asset_type: BLUE_CHIP
          "0xe7c53ffd03eb6cef7d208bc4c13446c76d1e5884", # oracle_address
          True, # is_active
        ],
        # CRV:
        [
          "0x11cdb42b0eb46d95f990bedd4695a6e3fa034978", # asset_address
          2, # asset_type: BLUE_CHIP
          "0xaebda2c976cfd1ee1977eac079b4382acb849325", # oracle_address
          True, # is_active
        ],
        # FXS:
        [
          "0x9d2f299715d94d8a7e6f5eaa8e654e8c74a988a7", # asset_address
          2, # asset_type: BLUE_CHIP
          "0x36a121448d74fa81450c992a1a44b9b7377cd3a5", # oracle_address
          True, # is_active
        ],
        # GMX:
        [
          "0xfc5a1a6eb076a2c7ad06ed22c90d7e710e35ad0a", # asset_address
          2, # asset_type: BLUE_CHIP
          "0xdb98056fecfff59d032ab628337a4887110df3db", # oracle_address
          True, # is_active
        ],
        # ARB:
        [
          "0x912ce59144191c1204e64559fe8253a0e49e6548", # asset_address
          2, # asset_type: BLUE_CHIP
          "0xb2a824043730fe05f3da2efafa1cbbe83fa548d6", # oracle_address
          True, # is_active
        ],
        # LDO:
        [
          "0x13ad51ed4f1b7e9dc168d8a00cb3f4ddd85efa60", # asset_address
          2, # asset_type: BLUE_CHIP
          "0xa43a34030088e6510feccfb77e88ee5e7ed0fe64", # oracle_address
          True, # is_active
        ],
      ]
    not_whitelisted_token_address_example: "0x09e18590e8f76b6cf471b3cd75fe1a1a9d2b2c2b" # AIDOGE - This token must have a pair created at the used dex
strategy-params:
  buy_percentages: [500, 500] #5% 5%
  buy_frequency: 0 # Daily
protocol-params:
  treasury_fixed_fee_on_vault_creation: 100_000_000_000_000 # Ether amount (0.001)
  creator_percentage_fee_on_deposit: 50 #0.50%
  treasury_percentage_fee_on_balance_update: 300 #3%
  max_slippage_perc: 50 #0.5%
  worker_max_expected_gas_units_wei: 100 # unrealistically low value in order to avoid minimum allowed during the testing proccess
  # The following parameters must be changed if strategy manager default parameters change
  number_of_days_per_buy_frequency:
    0: 1 # DAILY
    1: 7 # WEEKLY
    2: 14 # BI_WEEKLY
    3: 30 # MONTHLY
  max_number_of_actions_per_frequency:
    0: 60 # DAILY
    1: 52 # WEEKLY
    2: 26 # BI_WEEKLY
    3: 12 # MONTHLY
  gas_cost_safety_factors:
    0: 1000 # THIRTY
    1: 2250 # NINETY
    2: 3060 # ONE_HUNDRED_AND_EIGHTY
    3: 4000 # THREE_HUNDRED_AND_SIXTY_FIVE
  deposit_token_price_safety_factor:
    0: # STABLE
      0: 1000 # THIRTY
      1: 1000 # NINETY
      2: 1000 # ONE_HUNDRED_AND_EIGHTY
      3: 1000 # THREE_HUNDRED_AND_SIXTY_FIVE
    1: # ETH_BTC
      0: 1000 # THIRTY
      1: 1000 # NINETY
      2: 1000 # THREE_HUNDRED_AND_SIXTY_FIVE
      3: 1000 # THREE_HUNDRED_AND_SIXTY_FIVE
    2: # BLUE_CHIP
      0: 900 # THIRTY
      1: 800 # NINETY
      2: 650 # THREE_HUNDRED_AND_SIXTY_FIVE
      3: 500 # THREE_HUNDRED_AND_SIXTY_FIVE
